services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: virtual_card
      POSTGRES_USER: virtual_card
      POSTGRES_PASSWORD: virtual_card
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: