spring.application.name=virtual-card-issuance-platform

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/virtual_card}
spring.datasource.username=${DB_USERNAME:virtual_card}
spring.datasource.password=${DB_PASSWORD:virtual_card}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
idempotency.retention-seconds=86400
idempotency.cleanup-interval-ms=3600000

management.endpoints.web.exposure.include=health,metrics
logging.pattern.level=%5p [${spring.application.name:},%X{requestId:-}]
